package com.dxc.cherry.classes.parser;

/**
 * The "Token" class represents a single token generated by the Lexer. Each token consists of a type and a lexeme(the value of the token).
 * The type indicates the category of the token, and the value is the actual text representation of the token in the input expression.
 */
public class Token {
    public enum Type {
        NUMBER,
        PLUS,
        MINUS,
        MULTIPLY,
        DIVIDE,
        LEFT_PAREN,
        RIGHT_PAREN,
        POWER,
        END_OF_INPUT
    }
    private final Type type;
    private final String lexeme;

    public Token(Type type, String lexeme) {
        this.type = type;
        this.lexeme = lexeme;
    }

    public Type getType() {
        return type;
    }

    
    public String getLexeme() {
        return lexeme;
    }

    @Override
    public String toString() {
        return "Token{" +
                "type=" + type +
                ", lexeme='" + lexeme + '\'' +
                '}';
    }

    // A method that checks if the token is an operator
    public boolean isOperator() {
        return type == Type.PLUS || type == Type.MINUS || type == Type.MULTIPLY || type == Type.DIVIDE || type == Type.POWER;
    }

    // A method that checks if the token has higher precedence than another token
    public boolean hasHigherPrecedence(Token other) {
        if (other == null) {
            return false;
        }
        if (type == Type.MULTIPLY || type == Type.DIVIDE || type == Type.POWER) {
            return other.type == Type.PLUS || other.type == Type.MINUS;
        }
        return false;
    }
}

